Add DCO check (#4636)
* DCO check workflow

Signed-off-by: Bhushan Sonawane <quic_bhushans@quicinc.com>

* Typo in comment

Signed-off-by: Bhushan Sonawane <quic_bhushans@quicinc.com>

* update typo

Signed-off-by: Bhushan Sonawane <quic_bhushans@quicinc.com>

---------

Signed-off-by: Bhushan Sonawane <quic_bhushans@quicinc.com>
Co-authored-by: Bhushan Sonawane <quic_bhushans@quicinc.com>

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -4,6 +4,39 @@ on:
   workflow_call:
 
 jobs:
+  dco-check:
+    # TODO: Replace with DCO app once available.
+    # ref: https://github.com/apps/dco/
+    name: Developer Certificate of Origin(DCO) check
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Check each commit for DCO
+        run: |
+          # Collect all commits in PR
+          commit_hashes=`git log --format="%H" origin/${{ github.base_ref }}..origin/${{ github.head_ref }}`
+
+          for commit_hash in $commit_hashes; do
+            # DCO check for each commit
+            author_name=`git log --format="%an" ${commit_hash} -1`
+            author_email=`git log --format="%ae" ${commit_hash} -1`
+            commit_msg=`git log --format="%b" ${commit_hash} -1`
+            dco_pattern="Signed-off-by: ${author_name} <${author_email}>"
+
+            # Check if author is indeed Signing off commit
+            if ! echo "${commit_msg}" | grep "${dco_pattern}"; then
+              commit_msg_short=`git log --pretty=oneline ${commit_hash} -1`
+              echo "DCO check failed for ${commit_msg_short}"
+              exit 1
+            fi
+          done
+
+          echo "DCO check successful" 
+
   docker-tag:
     name: Check if 'latest' tag could be used (no build docker images)
     runs-on: ubuntu-latest
